apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: aqua-pipeline
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent any
          stages {
          stage('Build') {
              steps {
                  script {
                      openshift.withCluster() {
                          openshift.withProject() {
                              openshift.newBuild('https://github.com/arctiqteam/weather-app#static')
                              sh 'sleep 10'
                              sh 'oc logs -f bc/weather-app'
                          }
                      }
                  }
              }
          }
              stage('Scan') {
                  steps {
                      script {
                          aqua customFlags: '', hideBase: false, hostedImage: 'cicd/weather-app:latest', localImage: '', locationType: 'hosted', notCompliesCmd: '', onDisallowed: 'fail', policies: '', register: false, registry: 'openshift', showNegligible: false
                      }
              }
           }
         }
        }
    type: JenkinsPipeline
  triggers: []
